concretecms/bedrock

.github/workflows/nodejs.yml

This is worth merging, but it's mostly a test for required linting on PRs

Rename the lint job to be more accurate

---

assets/account/js/frontend/components/Avatar/Cropper.vue
assets/cms/components/form/Toggle.vue
package.json
stories/forms/toggle.stories.js

See the stories file for usage. This will need to be modified to use the Icon component @mesparza5 is working on

Toggle vue component

---

assets/bedrock/js/frontend/locations/country-data-link.js

This fixes the first issue reported at https://github.com/concrete5/concrete5/pull/8539

Fix initializing country/province link

---

assets/cms/components/IconButton.vue

Fix iconbutton label position prop

---

assets/cms/scss/_forms.scss
assets/cms/scss/_panels.scss
assets/cms/scss/panels/pages/details/_location.scss

This pull requests adds new styling for the page panel locations requested by issue #8480

Adding panel page Locations styling

---

assets/cms/scss/panels/pages/details/_clipboard.scss

Tweaking a bit more the styling to math better the comp.

fixing styling to match comp

---

assets/cms/scss/_base.scss
assets/cms/scss/_nav.scss

Adding new styling to navigation

---

.github/workflows/nodejs.yml
.github/workflows/storybook.yml

This PR adds `feature/*` to the list of branches that get github actions

Run github actions on feature branch pull requests

---

assets/cms/js/calendar/event-selector.js
assets/cms/js/express/selector.js
assets/cms/js/sitemap/selector.js
assets/cms/js/users/selector.js

Fix FontAwesome close icon

---

assets/cms/js/alert.js
assets/cms/js/base.js
assets/cms/js/notifications-box.js
assets/cms/js/page-notification.js
assets/cms/js/pnotify.js
assets/cms/js/progressive-operations.js
assets/cms/scss/_hud.scss
assets/cms/scss/_variables.scss
package-lock.json
package.json

This PR addresses issue https://github.com/concrete5/concrete5/issues/8580
requires a companion PR https://github.com/concrete5/concrete5/pull/8763

Page notification update

---

assets/cms/components/gallery/ImageDetail.vue

Updating buttons to use our already defined button component.

Updating buttons

---

assets/cms/components/gallery/GalleryEdit.vue

Once this lands I'll open a PR to update the package-lock.json in concrete5

Remove design tab for now, add 'coming soon' text to settings tab

---

assets/cms/scss/panels/add/_blocks.scss

This is just one class name added to match the modifications in the add panel
Requires companion core pull request https://github.com/concrete5/concrete5/pull/8810

Added class name for proper styling of containers

---

package-lock.json
package.json

Install Ace js Library
Companion  PR: https://github.com/concrete5/concrete5/pull/8908

Fix HTML block for version 9

---

assets/cms/components/Breadcrumb.vue
assets/cms/components/Pagination.vue
assets/cms/components/file-manager/Chooser.vue
assets/cms/components/file-manager/Chooser/FileManager.vue
assets/cms/components/file-manager/Chooser/FileSets.vue
assets/cms/components/file-manager/Chooser/FileUpload.vue
assets/cms/components/file-manager/Chooser/Files.vue
assets/cms/components/file-manager/Chooser/Header.vue
assets/cms/components/file-manager/Chooser/RecentUploads.vue
assets/cms/components/file-manager/Chooser/SavedSearch.vue
assets/cms/components/file-manager/Chooser/Search.vue
assets/cms/components/file-manager/Uploader.vue
assets/cms/components/file-manager/Uploader/UploadFromComputer.vue
assets/cms/components/form/ConcreteFileDirectoryInput.vue
assets/cms/components/index.js

This PR adresses https://github.com/concrete5/concrete5/issues/8754
Requires PR https://github.com/concrete5/concrete5/pull/8980

Complete the new In-Page File Chooser Component

---

assets/cms/js/sitemap/sitemap.js

Companion of https://github.com/concrete5/concrete5/pull/8997

Migrate all concrete/tools/dashboard/* scripts into the routing/controller/view/system

---

assets/cms/components/file-manager/Chooser.vue
assets/cms/components/file-manager/Chooser/ExternalFileProvider.vue
assets/cms/components/file-manager/Chooser/Files.vue

This update contains the changes for the file managers vue component.

Add support for external file providers to the core

---

assets/cms/components/file-manager/Chooser/ExternalFileProvider.vue
assets/cms/components/file-manager/Chooser/Files.vue

Improvements for external file provider

---

assets/cms/scss/_dialogs.scss
assets/cms/scss/dialogs/_workflow-approve_page_preview.scss

Companion of https://github.com/concrete5/concrete5/pull/9075

Migrate all concrete/tools/workflow scripts into the routing/controller/view system

---

assets/conversations/js/frontend/attachments.js
assets/conversations/js/frontend/conversations.js

Companion of https://github.com/concrete5/concrete5/pull/8993

Migrate all concrete/tools/conversations/ scripts into the new routing/controller/view system

---

assets/cms/js/edit-mode/editmode.js
assets/cms/js/page-indexer.js

Companion of https://github.com/concrete5/concrete5/pull/9088

 Migrate top level tools scripts into the routing/controller/view system

---

.eslintrc.yml
assets/cms/js/edit-mode/editmode.js
assets/cms/js/sitemap/sitemap.js
assets/conversations/js/frontend/attachments.js
assets/conversations/js/frontend/conversations.js

See also https://github.com/concrete5/concrete5/pull/9163

Remove support for tools

---

assets/cms/components/form/ConcretePageInput.vue
assets/cms/js/sitemap/search.js

Required by https://github.com/concrete5/concrete5/pull/9176

Sitemap views: allow setting includeSystemPages on an instance basis 

---

assets/calendar/js/backend/duration.js
assets/cms/js/base.js
assets/cms/js/edit-mode/style-customizer/inline-toolbar.js
assets/cms/js/modifiable-ajax-bootstrap-select.js
assets/cms/js/modifiable-bootstrap-select.js
assets/cms/js/search/base.js
assets/cms/js/search/field-selector.js
assets/cms/js/sitemap/sitemap.js
assets/cms/scss/_selectize.scss

This pull request takes care of https://github.com/concrete5/concrete5/issues/8710
It requires the companion pull request https://github.com/concrete5/concrete5/pull/9177
Details on the Core pull request page

Replace selectize with bootstrap select

---

assets/cms/js/sitemap/sitemap-selector.js

This fix the checkbox selection in fancytree component.

Another fix in sitemap selector

---

assets/cms/js/sitemap/sitemap.js

Fix bug in the console if the page was copied or moved in the sitemap

Fix move & copy page in sitemap

---

assets/ckeditor/js/concrete/upload-image.js

A part of V9 version of https://github.com/concrete5/concrete5/pull/9577

Show error message when upload image failed via drag to CKEditor

---

assets/cms/js/tree.js

Minor security fixes

---

assets/cms/components/customizer/ColorPageCustomizerWidget.vue
assets/cms/components/customizer/FontFamilyPageCustomizerWidget.vue
assets/cms/components/customizer/ThemeCustomizer.vue
assets/cms/components/customizer/ThemeCustomizerPreview.vue
assets/cms/components/index.js
assets/cms/scss/bootstrap/_reboot.scss
assets/imagery/js/frontend/lightbox.js

Adding a new theme customizer preview component; support updates for improvements to the customizer to split the concept of presets and skins apart (letting us having much better Elemental backward compatibility, among other things.)

Updates to theme customizer (9.0rc)

---

assets/cms/js/jquery-awesome-rating.js

Updates the classes for font-awesome5
Mainly for the conversation block / ratings

Update jquery-awesome rating icons

---

assets/cms/components/form/PasswordInput.vue
assets/cms/components/index.js

Vue Component approach for implementing password toggler.
companion pull request in the core: https://github.com/concretecms/concretecms/pull/10746

adding PasswordInput componnet

---

assets/cms/scss/_base.scss
assets/cms/scss/_color-picker.scss
assets/cms/scss/_inline-toolbar.scss

make color picker design in line with bs forms:

fix color picker layout

---

assets/cms/components/file-manager/Uploader/UploadFromComputer.vue

- add `startUploading()` method
- add `files-ready-to-upload` Vue event
- add uploaded file IDs to the `upload-complete` Vue event

Improve UploadFromComputer component

---

assets/cms/components/form/ConcreteUserInput.vue

Concrete user input fixes

---

assets/cms/components/form/ConcreteGroupInput.vue
assets/cms/components/groups/Chooser.vue
assets/cms/components/index.js
assets/cms/js/users.js
assets/cms/js/users/group-manager.js

Companion of https://github.com/concretecms/concretecms/pull/10966

Add group selector

---

assets/cms/components/form/ConcreteFileInput.vue

Fix https://github.com/concretecms/concretecms/issues/10990

Fix ConcreteFileInput when input name contains square brackets
