concretecms/bedrock

- assets/cms/js/base.js
- assets/documents/js/frontend.js
On case-sensitive operating systems, we have this error:
```
ERROR in ./node_modules/@concretecms/bedrock/assets/cms/js/base.js
Module not found: Error: Can't resolve 'NProgress'
```
Let's fix this
> Fix importing NProgress

- assets/cms/scss/_bootstrap-overrides.scss
- assets/cms/scss/_buttons.scss
Per Gary Cribb's comps, our button styles should be 14px (in Sketch), with some tweaked padding and font weight values.
I have updated bedrock to get even closer to these sketch values. 
Top image is a screenshot from sketch, bottom is the rendered button. Overlayed they are 99.9% the same, differences due to browser font rendering and sketch rendering.
> Better button consistency

- assets/calendar/js/backend/duration.js
- assets/cms/js/asset-loader.js
- assets/cms/js/edit-mode/area.js
- assets/cms/js/edit-mode/block.js
- assets/cms/js/edit-mode/blocktype.js
- assets/cms/js/edit-mode/container.js
- assets/cms/js/edit-mode/containerblock.js
- assets/cms/js/edit-mode/dragarea.js
- assets/cms/js/edit-mode/duplicateblock.js
- assets/cms/js/edit-mode/editmode.js
- assets/cms/js/edit-mode/layout.js
- assets/cms/js/edit-mode/stack.js
- assets/cms/js/edit-mode/stackblock.js
- assets/cms/js/edit-mode/stackdisplay.js
- assets/cms/js/events.js
- assets/cms/js/help/dialog.js
- assets/cms/js/help/guide-manager.js
- assets/cms/js/help/launcher.js
- assets/cms/js/legacy-dialog.js
- assets/cms/js/search/field-selector.js
- assets/cms/js/toolbar.js
- assets/conversations/js/frontend/attachments.js
- assets/conversations/js/frontend/conversations.js
Building for prod in concrete5's repo would result in javascript errors. After digging it was clear that the cause was removing semicolons from the end of IIFEs so I've gone through and added them back.
This can also likely be resolved in a compliant way by adding leading semicolons, but we should just refactor as possible to get away from IIFEs entirely.
> Add semicolons to old IIFEs to allow prod building to work

- package.json
Windows doesn't accept single quotes to enclose parameter values, only double quotes.
> Fix linting JS files on Windows

- .storybook/preview-head.html
- .storybook/preview.js
I've gone back and forth with how we should include fontawesome in storybook and I've struggled to get the webfont working out of NPM. I think what we need is to set the `$fa-font-path` to something that webpack is set to render, but I haven't found the right combination of things to get that working.
Instead let's just include their official cdn version.
> Fix fontawesome by using their official CDN to serve webfonts

- assets/cms/components/IconButton.vue
The type defaults to 'button', which differs from the HTML spec where button defaults to type 'submit' if it's contained within a form.
> Update iconbutton to allow passing through button type

- assets/cms/components/IconButton.vue
Fix a mixup in prop names in the icon button component. We were using the `type` prop for two different things, instead I've added a new prop 'buttonType' that handles setting the `type='..'` value on the button.
> Fix a regression in iconbutton

- .github/workflows/storybook.yml
- .gitignore
Storybook wasn't able to build because it couldn't find the images referenced in  https://github.com/concrete5/bedrock/pull/48/files. We should be careful with these relative files and maybe switch to a different way of embedding them like base64 data urls.
This PR also adds a github action that builds storybook so that we can have a better chance at keeping it healthy.
> Fix storybook and add a github action that will build it for pull requests

- assets/cms/scss/_tooltips.scss
The position of tooltips is correct when relative to elements in dialogs, but it's wrong in other cases:
Removing `position: relative;` from the `ccm-tooltip-holder` element seems to fix this issue (but we have to set the z-index of contained tooltips):
> Fix tooltip positioning

- assets/cms/components/gallery/GalleryEdit.vue
- assets/cms/components/gallery/ImageCell.vue
- assets/cms/components/gallery/ImageDetail.vue
- Removing the confirmation dialog closes the block's window when editing in the page.
- Fixing and updating the buttons
> Gallery block removing confirmation dialog  and fixing buttons

- assets/cms/components/gallery/GalleryEdit.vue
- assets/cms/components/gallery/ImageCell.vue
- assets/cms/components/gallery/ImageDetail.vue
- stories/gallery/galleryEdit.stories.js
- Use icon-button for image adding
- Use file manager popup to add files
- Wrap the images in a container that makes sizing and positioning properly a little bit easier
- Add a `ref` to the cells so that we can scroll to them without needing an event triggered by the user. This is helpful for setting a newly edited image as active
- Switch `activeImage` tracker to track the active index rather than the image object
- Pass through choices so that we can initialize newly added images properly
- Don't show delete button if image isn't hovered
- Center and position the detail preview image in the left half of the dialog
> Gallery block component updates

- assets/cms/components/gallery/ImageCell.vue
- assets/cms/scss/file-manager/_image-cell.scss
This PR moves out the image cell's styling to `_image-cell.scss` With this change we are centralizing the styling so can be used globally.
> Moving styling out the component so can be re-usable glabally

- assets/cms/scss/jquery-ui/_theme.scss
We were missing these settings and images from our jquery-ui theme causing jquery ui icons to not show. 
There is a companion PR in the concrete5/concrete5 repo that adds a mix step to copy out the relevant images from jquery ui and builds assets.
> Add jquery ui base theme icons to our jquery ui theme

- assets/cms/components/file-manager/Chooser.vue
- assets/cms/components/file-manager/Chooser/Files.vue
- assets/cms/components/file-manager/Chooser/Sets.vue
As requested by #8754 this PR adds the File Sets Tab Component for the In Page File Chooser. 
We also modified the Recent Files Component and renamed it so can be usable across other components like in this case the File Sets component.
Note: This new File Sets component also needs an update in the core for the Routes that feed this component.
> Adds File Sets Tab - inPage File Chooser Component

- assets/cms/components/file-manager/Chooser.vue
- assets/cms/components/file-manager/Chooser/Search.vue
As requested by #8754 we are adding the Search Component for our In-Page File Chooser.
> Adding Search Component to In-Page File Chooser

- assets/cms/js/page-notification.js
We need this to handle buttons and links in notifications with a `class="dialog-launch"` attribute.
> Setup dialogs in notification dialogs

- package-lock.json
- package.json
Didn't make a PR for concrete5/concrete5 repo. I read this [documentation](https://documentation.concretecms.org/tutorials/submitting-user-interface-pull-requests-for-concrete5-version-9) but couldn't find the way how to apply updates of dependencies of bedrock on the main repo.
> Bump CKEditor from 4.15.1 to 4.16.1

- package-lock.json
- package.json
CKEditor 4.16.2 has some security updates that are highly recommended to apply.
https://ckeditor.com/cke4/release-notes
> Bump CKEditor from 4.16.1 to 4.16.2

- package-lock.json
- package.json
CKEditor 4.17.0 has some security fixes that are highly recommended to apply.
https://ckeditor.com/cke4/release-notes
> Bump CKEditor from 4.16.2 to 4.17.1

- assets/cms/js/toolbar.js
- assets/cms/scss/_toolbar.scss
- package.json
* Fix https://github.com/concrete5/concrete5/issues/10398
* Adding new direct exit toolbar event for better stack approval button showing.
> Misc Fixes 03/04

- assets/cms/scss/_base.scss
- assets/cms/scss/_nav-sidebar.scss
This contains the same as #245, but the code is placed in a separate file under a specific class name `nav-sidebar`.
In this case, the class should be added to the page containing the nav.
> express details page: add style to nav (2)

- assets/cms/js/alert.js
This "unsafe" data may contain HTML, and we may want to escape it.
By default we keep the previous behavior (that is, display messages as if they were in HTML format).
> Let users display Concrete dialogs that contains unsafe data

- .eslintrc.yml
Consider this code (it's [valid es2020](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)):
```JavaScript
parseInt(this.selectedGroup?.gID) || 0
```
The linter doesn't like this syntax: it fails with this error
```
Parsing error: Unexpected token .
```
What about configuring the linter so that it accepts the es2020 features?
PS: when we build the assets, it gets transpiled to this:
```JavaScript
parseInt(null===(n=this.selectedGroup)||void 0===n?void 0:n.gID)||0
```
which, in a less compressed version, can be read as
```JavaScript
parseInt(this.selectedGroup === null || this.selectedGroup === undefined ? undefined : this.selectedGroup.gID) || 0
```
So, it's compatible with old browsers (I've just tested it).
> Configure the linter so that it accepts ES2020 features

- assets/cms/js/toolbar.js
The elements in the dashboard pages marked with the `launch-tooltip` CSS class are configured more than once: [here](https://github.com/concretecms/concretecms/blob/369a7050380dfb01e335ada3bb6e160800554835/build/assets/themes/dashboard/js/main.js#L129-L134) and [here](https://github.com/concretecms/bedrock/blob/572c49957d638d55ebebc7d8ed79d9c6d86a88e9/assets/cms/js/toolbar.js#L63-L72).
The first time, bootstrap removed the `title` attribute, storing in in the tooltip configuration.
The second time, bootstrap doesn't fine the `title` attribute, so the tooltip won't be displayed.
The solution? Avoid double initialization of tooltips.
See also https://github.com/concretecms/concretecms/pull/10988
Fix https://github.com/concretecms/concretecms/issues/10944
> Avoid double tooltip initialization

- assets/cms/scss/_intelligent-search.scss
- assets/cms/scss/_toolbar.scss
- assets/cms/scss/_variables.scss
- assets/cms/scss/panels/_shared.scss
Theme developers may need to use the height of the `ccm-toolbar` element: what about introducing a new variable instead of manually using `48px`?
> Use $ccm-toolbar-height variable to represent the CCM Toolbar height

- assets/cms/js/tree.js
Nodes more than two levels deep do not get preselected on load even though they are present on the ajaxData object.
By checking the childNodes on expanding a node we can select the nodes afterwards. Added the collapse callback because unchecking nodes kept preselecting the nodes again due to the ajaxData.selected array. By removing unchecked key from the array this issue is also resolved.
> Fix fancytree multiselect level issue

- assets/cms/scss/_tooltips.scss
For example, this would turn
into
if tooltips contain new line characters.
> Preserve new lines in tooltips

- assets/cms/js/sitemap/sitemap.js
Tom Select [defaults to 50](https://tom-select.js.org/docs/#maxoptions) if not specified; `null` shows all
> Change default sitelist to all

- assets/ckeditor/js/concrete/inline.js
This change adds a confirmation prompt when the cancel button is used on the inline editor toolbar on a Content block, _and_ a change has been made to the contents  (uses the checkDirty function of CKEditor). If no change has been made, the cancel works immediately.
We realised lately that the cancel button is _right_ next to the save button, and it's very easy to mis-click and hit it, without any protection.  This means that users can make a large series of changes to a content block, and then accidentally lose it all, with no way to recover.  Much swearing can occur.
> Add check prompt when content block cancel used
